export const labels = [
  "person",
  "bicycle",
  "car",
  "motorcycle",
  "airplane",
  "bus",
  "train",
  "truck",
  "boat",
  "traffic light",
  "fire hydrant",
  "stop sign",
  "parking meter",
  "bench",
  "bird",
  "cat",
  "dog",
  "horse",
  "sheep",
  "cow",
  "elephant",
  "bear",
  "zebra",
  "giraffe",
  "backpack",
  "umbrella",
  "handbag",
  "tie",
  "suitcase",
  "frisbee",
  "skis",
  "snowboard",
  "sports ball",
  "kite",
  "baseball bat",
  "baseball glove",
  "skateboard",
  "surfboard",
  "tennis racket",
  "bottle",
  "wine glass",
  "cup",
  "fork",
  "knife",
  "spoon",
  "bowl",
  "banana",
  "apple",
  "sandwich",
  "orange",
  "broccoli",
  "carrot",
  "hot dog",
  "pizza",
  "donut",
  "cake",
  "chair",
  "couch",
  "potted plant",
  "bed",
  "dining table",
  "toilet",
  "tv",
  "laptop",
  "mouse",
  "remote",
  "keyboard",
  "cell phone",
  "microwave",
  "oven",
  "toaster",
  "sink",
  "refrigerator",
  "book",
  "clock",
  "vase",
  "scissors",
  "teddy bear",
  "hair drier",
  "toothbrush",
] as const;

export type Label = (typeof labels)[number];

const getIconWithLabel = (label: string) => {
  return <p className={`icon-[mdi--${label}] w-5 h-5 text-base-content`} />;
};

export const labelsIconMap: { [key in Label]: JSX.Element } = {
  person: getIconWithLabel("mdi-account"),
  bicycle: getIconWithLabel("bicycle"),
  car: getIconWithLabel("car"),
  motorcycle: getIconWithLabel("motorcycle"),
  airplane: getIconWithLabel("airplane"),
  bus: getIconWithLabel("bus"),
  train: getIconWithLabel("train"),
  truck: getIconWithLabel("truck"),
  boat: getIconWithLabel("boat"),
  "traffic light": getIconWithLabel("traffic"),
  "fire hydrant": getIconWithLabel("fire"),
  "stop sign": getIconWithLabel("stop"),
  "parking meter": getIconWithLabel("parking"),
  bench: getIconWithLabel("bench"),
  bird: getIconWithLabel("bird"),
  cat: getIconWithLabel("cat"),
  dog: getIconWithLabel("dog"),
  horse: getIconWithLabel("horse"),
  sheep: getIconWithLabel("sheep"),
  cow: getIconWithLabel("cow"),
  elephant: getIconWithLabel("elephant"),
  bear: getIconWithLabel("bear"),
  zebra: getIconWithLabel("zebra"),
  giraffe: getIconWithLabel("giraffe"),
  backpack: getIconWithLabel("backpack"),
  umbrella: getIconWithLabel("umbrella"),
  handbag: getIconWithLabel("handbag"),
  tie: getIconWithLabel("tie"),
  suitcase: getIconWithLabel("suitcase"),
  frisbee: getIconWithLabel("frisbee"),
  skis: getIconWithLabel("skis"),
  snowboard: getIconWithLabel("snowboard"),
  "sports ball": getIconWithLabel("sports"),
  kite: getIconWithLabel("kite"),
  "baseball bat": getIconWithLabel("baseball"),
  "baseball glove": getIconWithLabel("baseball"),
  skateboard: getIconWithLabel("skateboard"),
  surfboard: getIconWithLabel("surfboard"),
  "tennis racket": getIconWithLabel("tennis"),
  bottle: getIconWithLabel("bottle"),
  "wine glass": getIconWithLabel("wine"),
  cup: getIconWithLabel("cup"),
  fork: getIconWithLabel("fork"),
  knife: getIconWithLabel("knife"),
  spoon: getIconWithLabel("spoon"),
  bowl: getIconWithLabel("bowl"),
  banana: getIconWithLabel("banana"),
  apple: getIconWithLabel("apple"),
  sandwich: getIconWithLabel("sandwich"),
  orange: getIconWithLabel("orange"),
  broccoli: getIconWithLabel("broccoli"),
  carrot: getIconWithLabel("carrot"),
  "hot dog": getIconWithLabel("hot"),
  pizza: getIconWithLabel("pizza"),
  donut: getIconWithLabel("donut"),
  cake: getIconWithLabel("cake"),
  chair: getIconWithLabel("chair"),
  couch: getIconWithLabel("couch"),
  "potted plant": getIconWithLabel("potted"),
  bed: getIconWithLabel("bed"),
  "dining table": getIconWithLabel("dining"),
  toilet: getIconWithLabel("toilet"),
  tv: getIconWithLabel("tv"),
  laptop: getIconWithLabel("laptop"),
  mouse: getIconWithLabel("mouse"),
  remote: getIconWithLabel("remote"),
  keyboard: getIconWithLabel("keyboard"),
  "cell phone": getIconWithLabel("cell"),
  microwave: getIconWithLabel("microwave"),
  oven: getIconWithLabel("oven"),
  toaster: getIconWithLabel("toaster"),
  sink: getIconWithLabel("sink"),
  refrigerator: getIconWithLabel("refrigerator"),
  book: getIconWithLabel("book"),
  clock: getIconWithLabel("clock"),
  vase: getIconWithLabel("vase"),
  scissors: getIconWithLabel("scissors"),
  "teddy bear": getIconWithLabel("teddy"),
  "hair drier": getIconWithLabel("hair"),
  toothbrush: getIconWithLabel("toothbrush"),
};

export const defaultLabelsJaLabelMap: { [key in Label]: string } = {
  person: "人間",
  bicycle: "自転車",
  car: "車",
  motorcycle: "バイク",
  airplane: "飛行機",
  bus: "バス",
  train: "電車",
  truck: "トラック",
  boat: "ボート",
  "traffic light": "信号機",
  "fire hydrant": "消火栓",
  "stop sign": "一時停止",
  "parking meter": "駐車メーター",
  bench: "ベンチ",
  bird: "鳥",
  cat: "猫",
  dog: "犬",
  horse: "馬",
  sheep: "羊",
  cow: "牛",
  elephant: "象",
  bear: "熊",
  zebra: "シマウマ",
  giraffe: "キリン",
  backpack: "バックパック",
  umbrella: "傘",
  handbag: "ハンドバッグ",
  tie: "ネクタイ",
  suitcase: "スーツケース",
  frisbee: "フリスビー",
  skis: "スキー板",
  snowboard: "スノーボード",
  "sports ball": "ボール",
  kite: "凧",
  "baseball bat": "バット",
  "baseball glove": "グローブ",
  skateboard: "スケートボード",
  surfboard: "サーフボード",
  "tennis racket": "テニスラケット",
  bottle: "ボトル",
  "wine glass": "ワイングラス",
  cup: "コップ",
  fork: "フォーク",
  knife: "ナイフ",
  spoon: "スプーン",
  bowl: "ボール",
  banana: "バナナ",
  apple: "りんご",
  sandwich: "サンドイッチ",
  orange: "オレンジ",
  broccoli: "ブロッコリー",
  carrot: "人参",
  "hot dog": "ホットドッグ",
  pizza: "ピザ",
  donut: "ドーナツ",
  cake: "ケーキ",
  chair: "椅子",
  couch: "ソファ",
  "potted plant": "植木",
  bed: "ベッド",
  "dining table": "テーブル",
  toilet: "トイレ",
  tv: "テレビ",
  laptop: "ノートパソコン",
  mouse: "マウス",
  remote: "リモコン",
  keyboard: "キーボード",
  "cell phone": "携帯電話",
  microwave: "電子レンジ",
  oven: "オーブン",
  toaster: "トースター",
  sink: "シンク",
  refrigerator: "冷蔵庫",
  book: "本",
  clock: "時計",
  vase: "花瓶",
  scissors: "はさみ",
  "teddy bear": "テディベア",
  "hair drier": "ドレッサー",
  toothbrush: "歯ブラシ",
};

export const labelsRGBMap: { [key in Label]: [number, number, number] } = {
  person: [0, 0, 0],
  bicycle: [255, 0, 0],
  car: [0, 255, 0],
  motorcycle: [0, 0, 255],
  airplane: [255, 255, 0],
  bus: [255, 0, 255],
  train: [0, 255, 255],
  truck: [255, 255, 255],
  boat: [128, 0, 0],
  "traffic light": [0, 128, 0],
  "fire hydrant": [0, 0, 128],
  "stop sign": [128, 128, 0],
  "parking meter": [128, 0, 128],
  bench: [0, 128, 128],
  bird: [128, 128, 128],
  cat: [64, 0, 0],
  dog: [0, 64, 0],
  horse: [0, 0, 64],
  sheep: [64, 64, 0],
  cow: [0, 64, 64],
  elephant: [64, 0, 64],
  bear: [192, 0, 0],
  zebra: [0, 192, 0],
  giraffe: [0, 0, 192],
  backpack: [192, 192, 0],
  umbrella: [192, 0, 192],
  handbag: [0, 192, 192],
  tie: [64, 192, 0],
  suitcase: [0, 64, 192],
  frisbee: [192, 64, 0],
  skis: [0, 192, 64],
  snowboard: [64, 0, 192],
  "sports ball": [64, 192, 192],
  kite: [192, 64, 64],
  "baseball bat": [64, 64, 192],
  "baseball glove": [192, 192, 64],
  skateboard: [64, 192, 192],
  surfboard: [192, 64, 192],
  "tennis racket": [192, 192, 192],
  bottle: [32, 0, 0],
  "wine glass": [0, 32, 0],
  cup: [0, 0, 32],
  fork: [32, 32, 0],
  knife: [0, 32, 32],
  spoon: [32, 0, 32],
  bowl: [96, 0, 0],
  banana: [0, 96, 0],
  apple: [0, 0, 96],
  sandwich: [96, 96, 0],
  orange: [0, 96, 96],
  broccoli: [96, 0, 96],
  carrot: [32, 96, 0],
  "hot dog": [0, 32, 96],
  pizza: [96, 32, 0],
  donut: [0, 96, 32],
  cake: [32, 0, 96],
  chair: [32, 96, 96],
  couch: [96, 32, 96],
  "potted plant": [96, 96, 32],
  bed: [32, 32, 96],
  "dining table": [96, 96, 96],
  toilet: [16, 0, 0],
  tv: [0, 16, 0],
  laptop: [0, 0, 16],
  mouse: [16, 16, 0],
  remote: [0, 16, 16],
  keyboard: [16, 0, 16],
  "cell phone": [48, 0, 0],
  microwave: [0, 48, 0],
  oven: [0, 0, 48],
  toaster: [48, 48, 0],
  sink: [0, 48, 48],
  refrigerator: [48, 0, 48],
  book: [16, 48, 0],
  clock: [0, 16, 48],
  vase: [48, 16, 0],
  scissors: [16, 0, 48],
  "teddy bear": [48, 48, 16],
  "hair drier": [16, 48, 48],
  toothbrush: [48, 16, 48],
};

export const getColorStr = (label: Label, alpha: number = 1.0) => {
  const [r, g, b] = labelsRGBMap[label];
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
};
